name: Node.js Security CI & Docker Push (Performance Metrics Layer)

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test-and-scan:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run Tests
      run: npm test

    - name: Run Security Scan and Save to TXT
      run: node scripts/scan.js > scan_results.txt 2>&1
      continue-on-error: true

    - name: Upload Scan Results
      uses: actions/upload-artifact@v4
      with:
        name: security-scan-report
        path: scan_results.txt

  docker-push:
    name: Docker hub push
    runs-on: ubuntu-latest
    needs: test-and-scan
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/git_action_js
