name: Node.js Security CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run Tests
      run: npm test

    - name: Run Security Scan and Save to TXT
      run: node scripts/scan.js > scan_results.txt 2>&1
      continue-on-error: true

    - name: Upload Scan Results
      uses: actions/upload-artifact@v4
      with:
        name: security-scan-report
        path: scan_results.txt
